---
name: idr0018-neff-histopathology/experimentA
version: 1

defaults:
    # Should the column be processed when creating bulk-annotations (yes/no)
    include: no
    # Columns type of the bulk-annotations column
    type: string

    # If non-empty a string used to separate multiple fields in a column
    # White space will be stripped
    split:
    # Should this column be included in the clients (yes/no)
    includeclient: yes
    # Should this column be visible in the clients, if no the column should be
    # hidden in the client but will still be indexed by the searcher (yes/no)
    visible: yes
    # Should empty values be omitted from the client display
    omitempty: yes

columns:

  - name: Gene Identifier
    include: yes
  - name: Gene Identifier
    clientname: Gene Identifier URL
    clientvalue: http://www.ensembl.org/id/{{ value }}
    include: yes
  - name: Gene Symbol
    include: yes
  - name: Human Ortholog
    include: yes
  - name: Human Ortholog
    clientname: Human Ortholog URL
    clientvalue: http://www.ensembl.org/id/{{ value }}
    include: yes
  - name: Human Ortholog Gene Symbol
    include: yes
  - name: Phenotype 1
    include: yes
  - name: Phenotype 1 Term Name
    include: yes
  - name: Phenotype 1 Term Accession
    include: yes
  - name: Phenotype 1 Term Accession
    clientname: Phenotype 1 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 2
    include: yes
  - name: Phenotype 2 Term Name
    include: yes
  - name: Phenotype 2 Term Accession
    include: yes
  - name: Phenotype 2 Term Accession
    clientname: Phenotype 2 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 3
    include: yes
  - name: Phenotype 3 Term Name
    include: yes
  - name: Phenotype 3 Term Accession
    include: yes
  - name: Phenotype 3 Term Accession
    clientname: Phenotype 3 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 4
    include: yes
  - name: Phenotype 4 Term Name
    include: yes
  - name: Phenotype 4 Term Accession
    include: yes
  - name: Phenotype 4 Term Accession
    clientname: Phenotype 4 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 5
    include: yes
  - name: Phenotype 5 Term Name
    include: yes
  - name: Phenotype 5 Term Accession
    include: yes
  - name: Phenotype 5 Term Accession
    clientname: Phenotype 5 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 6
    include: yes
  - name: Phenotype 6 Term Name
    include: yes
  - name: Phenotype 6 Term Accession
    include: yes
  - name: Phenotype 6 Term Accession
    clientname: Phenotype 6 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 7
    include: yes
  - name: Phenotype 7 Term Name
    include: yes
  - name: Phenotype 7 Term Accession
    include: yes
  - name: Phenotype 7 Term Accession
    clientname: Phenotype 7 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 8
    include: yes
  - name: Phenotype 8 Term Name
    include: yes
  - name: Phenotype 8 Term Accession
    include: yes
  - name: Phenotype 8 Term Accession
    clientname: Phenotype 8 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 9
    include: yes
  - name: Phenotype 9 Term Name
    include: yes
  - name: Phenotype 9 Term Accession
    include: yes
  - name: Phenotype 9 Term Accession
    clientname: Phenotype 9 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 10
    include: yes
  - name: Phenotype 10 Term Name
    include: yes
  - name: Phenotype 10 Term Accession
    include: yes
  - name: Phenotype 10 Term Accession
    clientname: Phenotype 10 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 11
    include: yes
  - name: Phenotype 11 Term Name
    include: yes
  - name: Phenotype 11 Term Accession
    include: yes
  - name: Phenotype 11 Term Accession
    clientname: Phenotype 11 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 12
    include: yes
  - name: Phenotype 12 Term Name
    include: yes
  - name: Phenotype 12 Term Accession
    include: yes
  - name: Phenotype 12 Term Accession
    clientname: Phenotype 12 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 13
    include: yes
  - name: Phenotype 13 Term Name
    include: yes
  - name: Phenotype 13 Term Accession
    include: yes
  - name: Phenotype 13 Term Accession
    clientname: Phenotype 13 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 14
    include: yes
  - name: Phenotype 14 Term Name
    include: yes
  - name: Phenotype 14 Term Accession
    include: yes
  - name: Phenotype 14 Term Accession
    clientname: Phenotype 14 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 15
    include: yes
  - name: Phenotype 15 Term Name
    include: yes
  - name: Phenotype 15 Term Accession
    include: yes
  - name: Phenotype 15 Term Accession
    clientname: Phenotype 15 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 16
    include: yes
  - name: Phenotype 16 Term Name
    include: yes
  - name: Phenotype 16 Term Accession
    include: yes
  - name: Phenotype 16 Term Accession
    clientname: Phenotype 16 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 17
    include: yes
  - name: Phenotype 17 Term Name
    include: yes
  - name: Phenotype 17 Term Accession
    include: yes
  - name: Phenotype 17 Term Accession
    clientname: Phenotype 17 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 18
    include: yes
  - name: Phenotype 18 Term Name
    include: yes
  - name: Phenotype 18 Term Accession
    include: yes
  - name: Phenotype 18 Term Accession
    clientname: Phenotype 18 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 19
    include: yes
  - name: Phenotype 19 Term Name
    include: yes
  - name: Phenotype 19 Term Accession
    include: yes
  - name: Phenotype 19 Term Accession
    clientname: Phenotype 19 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 20
    include: yes
  - name: Phenotype 20 Term Name
    include: yes
  - name: Phenotype 20 Term Accession
    include: yes
  - name: Phenotype 20 Term Accession
    clientname: Phenotype 20 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 21
    include: yes
  - name: Phenotype 21 Term Name
    include: yes
  - name: Phenotype 21 Term Accession
    include: yes
  - name: Phenotype 21 Term Accession
    clientname: Phenotype 21 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 22
    include: yes
  - name: Phenotype 22 Term Name
    include: yes
  - name: Phenotype 22 Term Accession
    include: yes
  - name: Phenotype 22 Term Accession
    clientname: Phenotype 22 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 23
    include: yes
  - name: Phenotype 23 Term Name
    include: yes
  - name: Phenotype 23 Term Accession
    include: yes
  - name: Phenotype 23 Term Accession
    clientname: Phenotype 23 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 24
    include: yes
  - name: Phenotype 24 Term Name
    include: yes
  - name: Phenotype 24 Term Accession
    include: yes
  - name: Phenotype 24 Term Accession
    clientname: Phenotype 24 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 25
    include: yes
  - name: Phenotype 25 Term Name
    include: yes
  - name: Phenotype 25 Term Accession
    include: yes
  - name: Phenotype 25 Term Accession
    clientname: Phenotype 25 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 26
    include: yes
  - name: Phenotype 26 Term Name
    include: yes
  - name: Phenotype 26 Term Accession
    include: yes
  - name: Phenotype 26 Term Accession
    clientname: Phenotype 26 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 27
    include: yes
  - name: Phenotype 27 Term Name
    include: yes
  - name: Phenotype 27 Term Accession
    include: yes
  - name: Phenotype 27 Term Accession
    clientname: Phenotype 27 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 28
    include: yes
  - name: Phenotype 28 Term Name
    include: yes
  - name: Phenotype 28 Term Accession
    include: yes
  - name: Phenotype 28 Term Accession
    clientname: Phenotype 28 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 29
    include: yes
  - name: Phenotype 29 Term Name
    include: yes
  - name: Phenotype 29 Term Accession
    include: yes
  - name: Phenotype 29 Term Accession
    clientname: Phenotype 29 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 30
    include: yes
  - name: Phenotype 30 Term Name
    include: yes
  - name: Phenotype 30 Term Accession
    include: yes
  - name: Phenotype 30 Term Accession
    clientname: Phenotype 30 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 31
    include: yes
  - name: Phenotype 31 Term Name
    include: yes
  - name: Phenotype 31 Term Accession
    include: yes
  - name: Phenotype 31 Term Accession
    clientname: Phenotype 31 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 32
    include: yes
  - name: Phenotype 32 Term Name
    include: yes
  - name: Phenotype 32 Term Accession
    include: yes
  - name: Phenotype 32 Term Accession
    clientname: Phenotype 32 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 33
    include: yes
  - name: Phenotype 33 Term Name
    include: yes
  - name: Phenotype 33 Term Accession
    include: yes
  - name: Phenotype 33 Term Accession
    clientname: Phenotype 33 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 34
    include: yes
  - name: Phenotype 34 Term Name
    include: yes
  - name: Phenotype 34 Term Accession
    include: yes
  - name: Phenotype 34 Term Accession
    clientname: Phenotype 34 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 35
    include: yes
  - name: Phenotype 35 Term Name
    include: yes
  - name: Phenotype 35 Term Accession
    include: yes
  - name: Phenotype 35 Term Accession
    clientname: Phenotype 35 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 36
    include: yes
  - name: Phenotype 36 Term Name
    include: yes
  - name: Phenotype 36 Term Accession
    include: yes
  - name: Phenotype 36 Term Accession
    clientname: Phenotype 36 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 37
    include: yes
  - name: Phenotype 37 Term Name
    include: yes
  - name: Phenotype 37 Term Accession
    include: yes
  - name: Phenotype 37 Term Accession
    clientname: Phenotype 37 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 38
    include: yes
  - name: Phenotype 38 Term Name
    include: yes
  - name: Phenotype 38 Term Accession
    include: yes
  - name: Phenotype 38 Term Accession
    clientname: Phenotype 38 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 39
    include: yes
  - name: Phenotype 39 Term Name
    include: yes
  - name: Phenotype 39 Term Accession
    include: yes
  - name: Phenotype 39 Term Accession
    clientname: Phenotype 39 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 40
    include: yes
  - name: Phenotype 40 Term Name
    include: yes
  - name: Phenotype 40 Term Accession
    include: yes
  - name: Phenotype 40 Term Accession
    clientname: Phenotype 40 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 41
    include: yes
  - name: Phenotype 41 Term Name
    include: yes
  - name: Phenotype 41 Term Accession
    include: yes
  - name: Phenotype 41 Term Accession
    clientname: Phenotype 41 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 42
    include: yes
  - name: Phenotype 42 Term Name
    include: yes
  - name: Phenotype 42 Term Accession
    include: yes
  - name: Phenotype 42 Term Accession
    clientname: Phenotype 42 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 43
    include: yes
  - name: Phenotype 43 Term Name
    include: yes
  - name: Phenotype 43 Term Accession
    include: yes
  - name: Phenotype 43 Term Accession
    clientname: Phenotype 43 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 44
    include: yes
  - name: Phenotype 44 Term Name
    include: yes
  - name: Phenotype 44 Term Accession
    include: yes
  - name: Phenotype 44 Term Accession
    clientname: Phenotype 44 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 45
    include: yes
  - name: Phenotype 45 Term Name
    include: yes
  - name: Phenotype 45 Term Accession
    include: yes
  - name: Phenotype 45 Term Accession
    clientname: Phenotype 45 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 46
    include: yes
  - name: Phenotype 46 Term Name
    include: yes
  - name: Phenotype 46 Term Accession
    include: yes
  - name: Phenotype 46 Term Accession
    clientname: Phenotype 46 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 47
    include: yes
  - name: Phenotype 47 Term Name
    include: yes
  - name: Phenotype 47 Term Accession
    include: yes
  - name: Phenotype 47 Term Accession
    clientname: Phenotype 47 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 48
    include: yes
  - name: Phenotype 48 Term Name
    include: yes
  - name: Phenotype 48 Term Accession
    include: yes
  - name: Phenotype 48 Term Accession
    clientname: Phenotype 48 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes

 
# Advanced options (experimental)
advanced:
     # If a map-annotation is attached to a well also attach it to all images
     # in the well
     well_to_images: yes
