#!/usr/bin/env python

import sys
import os
import errno
import make_screen

ROOT = "/idr/filesets/idr0013-neumann-mitocheck/20150916-mitocheck-analysis/analysis/mitocheck"
SCREENS_DIR = "screens"


def main(argv):
    try:
        os.makedirs(SCREENS_DIR)
    except OSError as e:
        if e.errno == errno.ENOENT:
            pass
    basenames = os.listdir(ROOT)
    with open("statsB.txt", "w") as fo:
        for bn in basenames:
            plate_name = bn.split("--")[0]
            d = os.path.join(ROOT, bn)
            if not os.path.isdir(d):
                continue
            data_d = os.path.join(d, "hdf5")
            if not os.path.isdir(data_d):
                fo.write("%s\t0\n" % d)
                sys.stderr.write("%s: no hdf5 data\n" % d)
                continue
            n_files = sum(1 for _ in os.listdir(data_d) if _.endswith(".ch5"))
            fo.write("%s\t%d\n" % (d, n_files))
            screen_fn = os.path.join(SCREENS_DIR, "%s.screen" % bn)
            make_screen.main(["dummy", data_d, "-o", screen_fn, "-p", plate_name])
            with open("../screenB/plates/%s" % plate_name, "w") as plate_file:
                plate_file.write("idr0013-neumann-mitocheck/" + screen_fn)


if __name__ == "__main__":
    main(sys.argv)
