---
name: idr0006-fong-nuclearbodies
version: 1

defaults:
    # Should the column be processed when creating bulk-annotations (yes/no)
    include: no
    # Columns type of the bulk-annotations column
    type: string

    # If non-empty a string used to separate multiple fields in a column
    # White space will be stripped
    split:
    # Should this column be included in the clients (yes/no)
    includeclient: yes
    # Should this column be visible in the clients, if no the column should be
    # hidden in the client but will still be indexed by the searcher (yes/no)
    visible: yes
    # Should empty values be omitted from the client display
    omitempty: yes

columns:

  - name: hORFeome V5.1 Identifier
    include: yes
  - name: hORFeome V5.1 Identifier
    clientname: hORFeome V5.1 Identifier URL
    clientvalue: http://horfdb.dfci.harvard.edu/hv5/index.php?page=getresults&by=detail&qury={{ value }}
    include: yes    
  - name: Gene Identifier
    include: yes
  - name: Gene Identifier
    clientname: Gene Identifier URL
    clientvalue: http://www.ncbi.nlm.nih.gov/gene/{{ value }}
    include: yes
  - name: Gene Symbol
    include: yes
  - name: Phenotype
    include: yes
  - name: Phenotype Term Name
    include: yes
  - name: Phenotype Term Accession
    include: yes
  - name: Phenotype Term Accession
    clientname: Phenotype Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes

# Advanced options (experimental)
advanced:
    # If a map-annotation is attached to a well also attach it to all images
    # in the well
    well_to_images: yes
