#!/usr/bin/env python

import sys
import os
import errno
import make_screen

ROOT = "/uod/idr/filesets/idr0033-rohban-pathways/20170214-original"
SUBDIRS = ["images", "images_illum_corrected"]
PLATE_DIRS = ["41744", "41749", "41754", "41755", "41756", "41757"]


def main(argv):
    this_dir = os.path.dirname(os.path.abspath(__file__))
    parent = os.path.dirname(this_dir)
    screens_dir = os.path.join(parent, "screens")
    plates_fn = os.path.join(parent, "screenA", "idr0033-screenA-plates.tsv")
    rel_screens_dir = os.path.join(os.pardir, "screens")  # wrt plates_fn
    try:
        os.makedirs(screens_dir)
        os.makedirs(os.path.dirname(plates_fn))
    except OSError as e:
        if e.errno == errno.EEXIST:
            pass
    with open(plates_fn, "w") as fp:
        for tag in "", "_illum_corrected":
            subd = "images" + tag
            for plated in PLATE_DIRS:
                name = plated + tag
                d = os.path.join(ROOT, subd, plated)
                screen_fn = os.path.join(screens_dir, "%s.screen" % name)
                make_screen.main(["dummy", d, "-o", screen_fn, "-p", name])
                fp.write("%s\t%s.screen\n" %
                         (name, os.path.join(rel_screens_dir, name)))


if __name__ == "__main__":
    main(sys.argv)
