---
name: idr0021-lawo-pericentriolarmaterial/experimentA
version: 1

defaults:
    # Should the column be processed when creating bulk-annotations (yes/no)
    include: no
    # Columns type of the bulk-annotations column
    type: string

    # If non-empty a string used to separate multiple fields in a column
    # White space will be stripped
    split:
    # Should this column be included in the clients (yes/no)
    includeclient: yes
    # Should this column be visible in the clients, if no the column should be
    # hidden in the client but will still be indexed by the searcher (yes/no)
    visible: yes
    # Should empty values be omitted from the client display
    omitempty: yes

columns:

  - name: Characteristics [Organism]
    clientname: Organism
    include: yes
  - name: Characteristics [Cell Line]
    clientname: Cell Line
    include: yes
  - name: Characteristics [Cell Cycle Phase]
    clientname: Cell Cycle Phase
    include: yes
  - name: Experimental Condition [Antibody Target]
    clientname: Antibody Target
    include: yes
  - name: Comment [Targeted Protein]
    clientname: Targeted Protein
    include: yes
  - name: Comment [Targeted Protein]
    clientname: Targeted Protein URL
    clientvalue: http://www.ebi.ac.uk/pdbe/entry/search/index?text:{{ value }}
    include: yes
  - name: Comment [Gene Identifier]
    clientname: Gene Identifier
    include: yes
  - name: Comment [Gene Identifier]
    clientname: Gene Identifier URL
    clientvalue: http://www.ensembl.org/id/{{ value }}
    include: yes
  - name: Comment [Gene Symbol]
    clientname: Gene Symbol
    include: yes
  - name: Comment [Gene Symbol Synonyms]
    clientname: Gene Symbol Synonyms
    include: yes
  - name: Comment [Gene Annotation Comments]
    clientname: Gene Annotation Comments
    include: yes
  - name: Channels
    include: yes
  - name: Has Phenotype
    include: yes
  - name: Phenotype Annotation Level
    include: yes
  - name: Phenotype 1
    clientname: Phenotype
    include: yes
  - name: Phenotype 1 Term Name
    clientname: Phenotype Term Name
    include: yes
  - name: Phenotype 1 Term Accession
    clientname: Phenotype Term Accession
    include: yes
  - name: Phenotype 1 Term Accession
    clientname: Phenotype Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
 
# Advanced options (experimental)
advanced:
     # If a map-annotation is attached to a well also attach it to all images
     # in the well
     well_to_images: yes
