#!/usr/bin/env python

import sys
import os
import errno
import glob

import make_screen

ROOT = "/idr/filesets/idr0015-UNKNOWN-taraoceans/20150918-tara/RAW_DATA/"

SCREENS_DIR = os.path.join(os.pardir, "screenA/patterns")
PLATES_DIR = os.path.join(os.pardir, "screenA/plates")
ABS_SCREENS_DIR = "/idr/versions/demo/metadata/idr0015-UNKNOWN-taraoceans/screenA/patterns"

PLATE = "Tara"


def main(argv):
    try:
        os.makedirs(SCREENS_DIR)
        os.makedirs(PLATES_DIR)
    except OSError as e:
        if e.errno == errno.ENOENT:
            pass
    total = len(glob.glob(os.path.join(ROOT, "*/slide--S00/chamber*")))
    current = 0
    with open("stats.txt", "w") as fo:
        for subd in os.listdir(ROOT):
            head = subd
            subd = os.path.join(ROOT, subd, "slide--S00")
            if not os.path.isdir(subd):
                sys.stderr.write("WARNING: %r missing\n" % (subd,))
                continue
            for data_dir in os.listdir(subd):
                current += 1
                if not data_dir.startswith("chamber"):
                    continue
                tail = data_dir
                data_dir = os.path.join(subd, data_dir)
                print "doing %s [%d/%d]" % (data_dir, current, total)
                plate_tag = "%s_%s" % (head, tail)
                screen_bn = "%s.screen" % plate_tag
                screen_fn = os.path.join(SCREENS_DIR, screen_bn)
                n_wells = sum(1 for _ in os.listdir(data_dir)
                              if _.startswith("field"))
                if n_wells == 12:
                    continue  # special dirs we've been told to ignore
                fo.write("%s\t%d\n" % (data_dir, n_wells))
                make_screen.main([
                    "dummy", data_dir, "-o", screen_fn, "-p", PLATE
                ])
                plate_fn = os.path.join(PLATES_DIR, plate_tag)
                with open(plate_fn, "w") as plate_file:
                    plate_file.write("%s/%s\n" % (ABS_SCREENS_DIR, screen_bn))


if __name__ == "__main__":
    main(sys.argv)
