---
name: idr0001-graml-sysgro
version: 1

defaults:
    # Should the column be processed when creating bulk-annotations (yes/no)
    include: no
    # Columns type of the bulk-annotations column
    type: string

    # If non-empty a string used to separate multiple fields in a column
    # White space will be stripped
    split:
    # Should this column be included in the clients (yes/no)
    includeclient: yes
    # Should this column be visible in the clients, if no the column should be
    # hidden in the client but will still be indexed by the searcher (yes/no)
    visible: yes
    # Should empty values be omitted from the client display
    omitempty: yes

columns:

  - name: Gene Identifier
    include: yes
  - name: Strain Name
    include: yes
  - name: Gene Symbol
    include: yes
  - name: Phenotype 1
    include: yes
  - name: Ontology Term Name 1a
    include: yes
  - name: Term Source Accession 1a
    include: yes
  - name: Ontology Term Name 1b
    include: yes
  - name: Term Source Accession 1b
    include: yes
  - name: Phenotype 2
    include: yes
  - name: Ontology Term Name 2a
    include: yes
  - name: Term Source Accession 2a
    include: yes
  - name: Ontology Term Name 2b
    include: yes
  - name: Term Source Accession 2b
    include: yes
  - name: Phenotype 3
    include: yes
  - name: Ontology Term Name 3a
    include: yes
  - name: Term Source Accession 3a
    include: yes
  - name: Ontology Term Name 3b
    include: yes
  - name: Term Source Accession 3b
    include: yes
  - name: Phenotype 4
    include: yes
  - name: Ontology Term Name 4a
    include: yes
  - name: Term Source Accession 4a
    include: yes
  - name: Ontology Term Name 4b
    include: yes
  - name: Term Source Accession 4b
    include: yes
  - name: Phenotype 5
    include: yes
  - name: Ontology Term Name 5a
    include: yes
  - name: Term Source Accession 5a
    include: yes
  - name: Ontology Term Name 5b
    include: yes
  - name: Term Source Accession 5b
    include: yes
  - name: Phenotype 6
    include: yes
  - name: Ontology Term Name 6a
    include: yes
  - name: Term Source Accession 6a
    include: yes
  - name: Ontology Term Name 6b
    include: yes
  - name: Term Source Accession 6b
    include: yes
  - name: Phenotype 7
    include: yes
  - name: Ontology Term Name 7a
    include: yes
  - name: Term Source Accession 7a
    include: yes
  - name: Ontology Term Name 7b
    include: yes
  - name: Term Source Accession 7b
    include: yes 
