---
name: idr0001-graml-sysgro/screenA
version: 1

defaults:
    # Should the column be processed when creating bulk-annotations (yes/no)
    include: no
    # Columns type of the bulk-annotations column
    type: string

    # If non-empty a string used to separate multiple fields in a column
    # White space will be stripped
    split:
    # Should this column be included in the clients (yes/no)
    includeclient: yes
    # Should this column be visible in the clients, if no the column should be
    # hidden in the client but will still be indexed by the searcher (yes/no)
    visible: yes
    # Should empty values be omitted from the client display
    omitempty: yes

columns:

  - name: Gene Identifier
    include: yes
  - name: Gene Identifier
    clientname: Gene Identifier URL
    clientvalue: http://www.pombase.org/spombe/result/{{ value }}
    include: yes
  - name: Strain Name
    include: yes
  - name: Gene Symbol
    include: yes
  - name: Phenotype 1
    include: yes
  - name: Phenotype Term Name 1a
    include: yes
  - name: Phenotype Term Accession 1a
    include: yes
  - name: Phenotype Term Accession 1a
    clientname: Phenotype Term Accession 1a URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype Term Name 1b
    include: yes
  - name: Phenotype Term Accession 1b
    include: yes
  - name: Phenotype Term Accession 1b
    clientname: Phenotype Term Accession 1b URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 2
    include: yes
  - name: Phenotype Term Name 2a
    include: yes
  - name: Phenotype Term Accession 2a
    include: yes
  - name: Phenotype Term Accession 2a
    clientname: Phenotype Term Accession 2a URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype Term Name 2b
    include: yes
  - name: Phenotype Term Accession 2b
    include: yes
  - name: Phenotype Term Accession 2b
    clientname: Phenotype Term Accession 2b URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 3
    include: yes
  - name: Phenotype Term Name 3a
    include: yes
  - name: Phenotype Term Accession 3a
    include: yes
  - name: Phenotype Term Accession 3a
    clientname: Phenotype Term Accession 3a URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype Term Name 3b
    include: yes
  - name: Phenotype Term Accession 3b
    include: yes
  - name: Phenotype Term Accession 3b
    clientname: Phenotype Term Accession 3b URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 4
    include: yes
  - name: Phenotype Term Name 4a
    include: yes
  - name: Phenotype Term Accession 4a
    include: yes
  - name: Phenotype Term Accession 4a
    clientname: Phenotype Term Accession 4a URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype Term Name 4b
    include: yes
  - name: Phenotype Term Accession 4b
    include: yes
  - name: Phenotype Term Accession 4b
    clientname: Phenotype Term Accession 4b URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 5
    include: yes
  - name: Phenotype Term Name 5a
    include: yes
  - name: Phenotype Term Accession 5a
    include: yes
  - name: Phenotype Term Accession 5a
    clientname: Phenotype Term Accession 5a URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype Term Name 5b
    include: yes
  - name: Phenotype Term Accession 5b
    include: yes
  - name: Phenotype Term Accession 5b
    clientname: Phenotype Term Accession 5b URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 6
    include: yes
  - name: Phenotype Term Name 6a
    include: yes
  - name: Phenotype Term Accession 6a
    include: yes
  - name: Phenotype Term Accession 6a
    clientname: Phenotype Term Accession 6a URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype Term Name 6b
    include: yes
  - name: Phenotype Term Accession 6b
    include: yes
  - name: Phenotype Term Accession 6b
    clientname: Phenotype Term Accession 6b URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 7
    include: yes
  - name: Phenotype Term Name 7a
    include: yes
  - name: Phenotype Term Accession 7a
    include: yes
  - name: Phenotype Term Accession 7a
    clientname: Phenotype Term Accession 7a URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype Term Name 7b
    include: yes
  - name: Phenotype Term Accession 7b
    include: yes
  - name: Phenotype Term Accession 7b
    clientname: Phenotype Term Accession 7b URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
    
# Advanced options (experimental)
advanced:
    # If a map-annotation is attached to a well also attach it to all images
    # in the well
    well_to_images: yes
