#!/usr/bin/env python

import sys
import os
import glob
import errno
import make_screen

ROOT = ("/uod/idr/filesets/idr0011-thorpe-Dad4/20150826-peter_thorpe/")


def main(argv):
    study_root = os.path.dirname(os.path.abspath(__file__))
    screens_dir = os.path.join(study_root, "screens")
    plates_fn = os.path.join(study_root, "screenA/idr0011-screenA-plates.tsv")
    try:
        os.makedirs(screens_dir)
        os.makedirs(os.path.dirname(plates_fn))
    except OSError as e:
        if e.errno == errno.ENOENT:
            pass

    basenames = glob.glob("%s/*/*/*" % ROOT)
    with open(plates_fn, "w") as fp:
        for bn in basenames:
            print bn
            screen_name = os.path.basename(bn)
            screen_fn = os.path.join(screens_dir, "%s.screen" % screen_name)
            make_screen.main(["dummy", bn, "-o", screen_fn, "-p", bn])
            fp.write("%s\t%s.screen\n" %
                     (screen_name, bn))


if __name__ == "__main__":
    main(sys.argv)
