#!/usr/bin/env python

import sys
import os
import glob
import errno
import make_screen

ROOT = ("/uod/idr/filesets/idr0011-thorpe-Dad4/20150826-peter_thorpe/")

SCREENS = {
    "A": (
        ("T37 x deletion library", 2, "*/"),
        ("Stinger plates-extra images screen T37 x deletion library", 1, "*/"),
    ),
    "B": (
        ("T34 x TS", 6, "*/"),
        ("Stinger plates-extra images screen T34 x TS", 1, ""),
        ("Stinger plates-extra images screen T34 x TS-more repeats", 1, ""),
    ),
}

def main(argv):
    study_root = os.path.dirname(os.path.abspath(__file__))
    screens_dir = os.path.join(study_root, "screens")
    for letter, directories in sorted(SCREENS.items()):

        tsv = "screen%s/idr0011-screen%s-plates.tsv" % (letter, letter)
        plates_fn = os.path.join(study_root, tsv)
        try:
            os.makedirs(screens_dir)
            os.makedirs(os.path.dirname(plates_fn))
        except OSError as e:
            if e.errno == errno.ENOENT:
                pass

        with open(plates_fn, "w") as fp:
            for directory, fields, extra in directories:
                basenames = glob.glob("%s%s/%s*" % (ROOT, directory, extra))
                for bn in basenames:
                    if not os.path.isdir(bn): continue
                    print bn
                    screen_name = os.path.basename(bn)
                    screen_fn = os.path.join(screens_dir, "%s.screen" % screen_name)
                    make_screen.main(["dummy", bn,
                                      "-o", screen_fn,
                                      "-p", bn,
                                      "-f", str(fields)])
                    fp.write("%s\t%s.screen\n" %
                        (screen_name, bn))


if __name__ == "__main__":
    main(sys.argv)
