#!/usr/bin/env python

import sys
import os
import errno

import make_screen


ROOT = "/uod/idr/filesets/idr0035-caie-drugresponse/images"


def mkdir_p(path):
    try:
        os.makedirs(path)
    except OSError as e:
        if e.errno == errno.EEXIST:
            pass


def main(argv):
    this_dir = os.path.dirname(os.path.abspath(__file__))
    parent = os.path.dirname(this_dir)
    screens_dir = os.path.join(parent, "screens")
    plates_fn = os.path.join(parent, "screenA", "idr0035-screenA-plates.tsv")
    rel_screens_dir = os.path.join(os.pardir, "screens")  # wrt plates_fn
    mkdir_p(screens_dir)
    mkdir_p(os.path.dirname(plates_fn))
    with open(plates_fn, "w") as fp:
        for name in os.listdir(ROOT):
            d = os.path.join(ROOT, name)
            screen_fn = os.path.join(screens_dir, "%s.screen" % name)
            make_screen.main(["dummy", d, "-o", screen_fn, "-p", name])
            fp.write("%s\t%s.screen\n" %
                     (name, os.path.join(rel_screens_dir, name)))


if __name__ == "__main__":
    main(sys.argv)
