---
name: idr0038-held-kidneylightsheet/experimentB
version: 1

defaults:
    # Should the column be processed when creating bulk-annotations (yes/no)
    include: no
    # Columns type of the bulk-annotations column
    type: string

    # If non-empty a string used to separate multiple fields in a column
    # White space will be stripped
    split:
    # Should this column be included in the clients (yes/no)
    includeclient: yes
    # Should this column be visible in the clients, if no the column should be
    # hidden in the client but will still be indexed by the searcher (yes/no)
    visible: yes
    # Should empty values be omitted from the client display
    omitempty: yes

columns:

  - name: Comment [Sample Description]
    clientname: Sample Description
    include: yes
  - name: Characteristics [Strain]
    clientname: Strain
    include: yes
  - name: Characteristics [Genotype]
    clientname: Genotype
    include: yes
  - name: Characteristics [Organism Part]
    clientname: Organism Part
    include: yes
  - name: Characteristics [Developmental Stage]
    clientname: Developmental Stage
    include: yes
  - name: Material Entity
    clientname: Material Type
    include: yes
  - name: Characterisics [Growth Condition]
    clientname: Growth Condition
    include: yes

  - name: Channels
    include: yes

  - name: Comment [Image File Type]
    clientname: Image File Type
    include: yes
  - name: Comment [Image Dimensions]
    clientname: Image Dimensions
    include: yes
  - name: Comment [Image File Comments]
    clientname: Image File Comments
    include: yes
######################################################################
# mapr groups
######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
      - name: Characteristics [Organism]
        clientname: Organism
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/compound
      columns:
      - name: Experimental Condition [Compound]
        clientname: Compound Name
        include: yes
      - name: Experimental Condition [Compound]
        clientname: Compound Name URL
        clientvalue: https://www.ncbi.nlm.nih.gov/pccompound?term={{ value|urlencode }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/compound/supplementary
      columns:
      - name: Experimental Condition [Dose]
        clientname: Dose
        include: yes

# Advanced options (experimental)
advanced:
    # If a map-annotation is attached to a well also attach it to all images
    # in the well
    well_to_images: yes

    # TODO: Primary key config should be in a global config
    ignore_missing_primary_key: yes
    primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
      - Organism
    - namespace: openmicroscopy.org/mapr/compound
      keys:
      - Compound Name
