#!/usr/bin/env python3

from __future__ import print_function

import csv
import re
import sys
from pathlib import Path

import h5py
import numpy as np

idr016_location = Path('/uod/idr/filesets/idr0016-wawer-bioactivecompoundprofiling')
feature_location = Path(
    '2016-02-01-features/bbbc022-Dataset_S3_image_features')

csv_image = idr016_location / feature_location / Path(
    'supplement_Per_Image.csv')

csv_objects = {}
for p in (idr016_location /
          feature_location).glob('supplement_Per_Object_[0-9]*.csv'):
    plate_id = re.search('supplement_Per_Object_(\d+).csv',
                         str(p)).group(1)
    csv_objects[plate_id] = p

# "latest" version is required to allow large numbers of columns;
# there's a 64KiB limit for older HDF versions.
f = h5py.File("idr016.h5", "w", libver='latest')


def determine_csv_dtype(files, plate=False):
    fieldnames = None
    coltypes = []

    float_sig_digits = re.compile('^-?0*\.?0*(\d+)0*\.?0*(e-?\d+)?$')

    for file in files:
        print('Checking CSV dtypes: %s' % (file))
        with open(str(file)) as csvfile:
            reader = csv.DictReader(csvfile)
            if fieldnames is None:
                fieldnames = reader.fieldnames
                for col in range(len(reader.fieldnames)):
                    typeinfo = {}
                    colname = reader.fieldnames[col]
                    typeinfo['field'] = colname
                    typeinfo['column'] = col
                    typeinfo['stype'] = None
                    typeinfo['smax'] = 0
                    typeinfo['min'] = None
                    typeinfo['max'] = None
                    typeinfo['sig-digits'] = 0
                    typeinfo['contains-blank'] = False
                    coltypes.append(typeinfo)
            else:
                if fieldnames != reader.fieldnames:
                    raise Exception("Field name mismatch between CSV files")

            for row in reader:
                for col in range(len(reader.fieldnames)):
                    typeinfo = coltypes[col]
                    value = row[typeinfo['field']]

                    if value == '':
                        typeinfo['contains-blank'] = True
                        continue

                    pv = None
                    try:
                        pv = int(value)
                        if typeinfo['stype'] is None:
                            typeinfo['stype'] = 'i'
                    except ValueError:
                        try:
                            pv = float(value)
                            if typeinfo['stype'] is None or \
                               typeinfo['stype'] == 'i':
                                typeinfo['stype'] = 'f'
                        except ValueError:
                            typeinfo['stype'] = 's'

                    if typeinfo['stype'] == 'f':
                        sigmatch = float_sig_digits.match(value)
                        if sigmatch:
                            sig = len(sigmatch.group(1))
                            if sig is None:
                                sig = 0
                            if typeinfo['sig-digits'] is None:
                                typeinfo['sig-digits'] = sig
                            else:
                                typeinfo['sig-digits'] = max(
                                    typeinfo['sig-digits'], sig)

                    if pv is not None:
                        if typeinfo['min'] is None:
                            typeinfo['min'] = pv
                        else:
                            typeinfo['min'] = min(typeinfo['min'], pv)
                        if typeinfo['max'] is None:
                            typeinfo['max'] = pv
                        else:
                            typeinfo['max'] = max(typeinfo['max'], pv)

                    slen = len(value.encode('utf-8'))
                    typeinfo['smax'] = max(typeinfo['smax'], slen)

            for col in range(len(reader.fieldnames)):
                try:
                    typeinfo = coltypes[col]
                    if typeinfo['stype'] == 'i' and \
                       typeinfo['contains-blank'] is True:
                        # No way to represent null values, so retain as text
                        typeinfo['dtype'] = (typeinfo['field'],
                                             'S' + str(typeinfo['smax']))
                    elif typeinfo['stype'] == 'i':
                        vmin = typeinfo['min']
                        vmax = typeinfo['max']
                        if vmin < 0:
                            if vmin >= -2**7+1 and vmax <= 2**7-1:
                                typeinfo['dtype'] = (typeinfo['field'], 'i1')
                            elif vmin >= -2**15+1 and vmax <= 2**15-1:
                                typeinfo['dtype'] = (typeinfo['field'], 'i2')
                            elif vmin >= -2**31+1 and vmax <= 2**31-1:
                                typeinfo['dtype'] = (typeinfo['field'], 'i4')
                            elif vmin >= -2**63+1 and vmax <= 2**63-1:
                                typeinfo['dtype'] = (typeinfo['field'], 'i8')
                            else:
                                raise Exception("Signed integer too large: " +
                                                "%s, %s/%s" %
                                                (typeinfo['field'],
                                                 vmin, vmax))
                        else:
                            if vmax <= 2**8-1:
                                typeinfo['dtype'] = (typeinfo['field'], 'u1')
                            elif vmax <= 2**16-1:
                                typeinfo['dtype'] = (typeinfo['field'], 'u2')
                            elif vmax <= 2**32-1:
                                typeinfo['dtype'] = (typeinfo['field'], 'u4')
                            elif vmax <= 2**64-1:
                                typeinfo['dtype'] = (typeinfo['field'], 'u8')
                            else:
                                raise Exception("Unsigned integer too large:" +
                                                "%s, %s/%s" %
                                                (typeinfo['field'],
                                                 vmin, vmax))
                    elif typeinfo['stype'] == 'f':
                        sig = typeinfo['sig-digits']
                        if sig <= 6:
                            typeinfo['dtype'] = (typeinfo['field'], 'f4')
                        elif sig <= 15:
                            typeinfo['dtype'] = (typeinfo['field'], 'f8')
                        else:
                            typeinfo['dtype'] = (typeinfo['field'], 'f16')
                            print("Float too large: %s, %s sig digits" %
                                  (typeinfo['field'], sig), file=sys.stderr)
                    else:
                        typeinfo['dtype'] = (typeinfo['field'],
                                             'S' + str(typeinfo['smax']))
                except Exception as e:
                    raise Exception("Invalid field %s" % (typeinfo['field']))

    dtype = np.dtype([col['dtype'] for col in coltypes])

    return dtype


# Images
print("Importing image data: %s" % (csv_image))
with open(str(csv_image)) as csvfile:
    dtype = determine_csv_dtype([csv_image])
    print(dtype)

    reader = csv.reader(csvfile)
    # skip header
    next(reader, None)

    ndata = []

    for row in reader:
        for col in range(len(dtype)):
            if row[col] == '' and dtype[col].kind == 'f':
                row[col] = 'nan'
        drow = np.array(tuple(row), dtype=dtype)
        ndata.append(drow)

    print("Writing feature data")
    id = f.create_dataset("Images", (len(ndata),),
                          maxshape=(None,), dtype=dtype,
                          chunks=(128,), compression='gzip',
                          data=ndata)
    print("Done")

# Objects

dtype = determine_csv_dtype(csv_objects.values(), plate=True)
print(dtype)
od = f.create_dataset("Objects", (0,), maxshape=(None,), dtype=dtype,
                      chunks=(128,), compression='gzip')
for plate in sorted(csv_objects.keys()):
    print("Importing object data: %s" % (plate))
    with open(csv_objects[plate], newline='') as csvfile:
        reader = csv.reader(csvfile)
        # skip header
        next(reader, None)

        ndata = []

        for row in reader:
            for col in range(len(dtype)):
                if row[col] == '' and dtype[col].kind == 'f':
                    row[col] = 'nan'
            drow = np.array(tuple(row), dtype=dtype)
            ndata.append(drow)

        od.resize((od.shape[0] + len(ndata),))

        print("Writing feature data")
        od[-len(ndata):] = ndata
        print("Done")
