---
name: idr0012-fuchs-cellmorph/screenB
version: 1

defaults:
    # Should the column be processed when creating bulk-annotations (yes/no)
    include: no
    # Columns type of the bulk-annotations column
    type: string

    # If non-empty a string used to separate multiple fields in a column
    # White space will be stripped
    split:
    # Should this column be included in the clients (yes/no)
    includeclient: yes
    # Should this column be visible in the clients, if no the column should be
    # hidden in the client but will still be indexed by the searcher (yes/no)
    visible: yes
    # Should empty values be omitted from the client display
    omitempty: yes

columns:

  - name: Characteristics [Organism]
    clientname: Organism
    include: yes
  - name: Characteristics [Cell Line]
    clientname: Cell Line
    include: yes
    
  - name: siRNA Pool Identifier
    include: yes
  - name: siRNA Identifier
    include: yes
  - name: siRNA Sequences
    include: yes
  - name: Reagent Design Gene Annotation Build
    include: yes
    
  - name: Gene Identifier
    include: yes
  - name: Gene Identifier
    clientname: Gene Identifier URL
    clientvalue: http://www.ncbi.nlm.nih.gov/gene/?term={{ value }}
    include: yes
  - name: Gene Symbol
    include: yes
  - name: Analysis Gene Annotation Build
    include: yes
    
  - name: Control Type
    include: yes
  - name: Control Comments
    include: yes
    
  - name: Channels
    include: yes
  - name: Comments
    include: yes
    
  - name: HeLa Phenotype
    include: yes
  - name: HeLa Reproducibility Between Primary and Validation screen
    include: yes
  - name: Qiagen Reproducibility Between HeLa and U2OS cells
    include: yes
  - name: Has Phenotype
    include: yes
  - name: Phenotype Annotation Level
    include: yes
    
  - name: Phenotype 1
    clientname: Phenotype
    include: yes
  - name: Phenotype 1 Term Name
    clientname: Phenotype Term Name
    include: yes
  - name: Phenotype 1 Term Accession
    clientname: Phenotype Term Accession
    include: yes
  - name: Phenotype 1 Term Accession
    clientname: Phenotype Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
    
  - name: Phenotype 2
    clientname: Phenotype
    include: yes
  - name: Phenotype 2 Term Name
    clientname: Phenotype Term Name
    include: yes
  - name: Phenotype 2 Term Accession
    clientname: Phenotype Term Accession
    include: yes
  - name: Phenotype 2 Term Accession
    clientname: Phenotype Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
    
  - name: Phenotype 3
    clientname: Phenotype
    include: yes
  - name: Phenotype 3 Term Name
    clientname: Phenotype Term Name
    include: yes
  - name: Phenotype 3 Term Accession
    clientname: Phenotype Term Accession
    include: yes
  - name: Phenotype 3 Term Accession
    clientname: Phenotype Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
    
  - name: Phenotype 4
    clientname: Phenotype
    include: yes
    
  - name: Phenotype 5
    include: yes
  - name: Phenotype 5 Term Name
    clientname: Phenotype Term Name
    include: yes
  - name: Phenotype 5 Term Accession
    clientname: Phenotype Term Accession
    include: yes
  - name: Phenotype 5 Term Accession
    clientname: Phenotype Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
    
  - name: Phenotype 6
    clientname: Phenotype
    include: yes
  - name: Phenotype 6 Term Name
    clientname: Phenotype Term Name
    include: yes
  - name: Phenotype 6 Term Accession
    clientname: Phenotype Term Accession
    include: yes
  - name: Phenotype 6 Term Accession
    clientname: Phenotype Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
    
  - name: Phenotype 7
    clientname: Phenotype
    include: yes
    
  - name: Phenotype 8
    clientname: Phenotype
    include: yes
  - name: Phenotype 8 Term Name
    clientname: Phenotype Term Name
    include: yes
  - name: Phenotype 8 Term Accession
    clientname: Phenotype Term Accession
    include: yes
  - name: Phenotype 8 Term Accession
    clientname: Phenotype Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
    
  - name: Phenotype 9
    clientname: Phenotype
    include: yes
  - name: Phenotype 9 Term Name
    clientname: Phenotype Term Name
    include: yes
  - name: Phenotype 9 Term Accession
    clientname: Phenotype Term Accession
    include: yes
  - name: Phenotype 9 Term Accession
    clientname: Phenotype Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes

    
# Advanced options (experimental)
advanced:
    # If a map-annotation is attached to a well also attach it to all images
    # in the well
    well_to_images: yes
