#!/usr/bin/env python

import sys
import os
import operator
from argparse import ArgumentParser

import make_symlink_patterns
from common import get_data_dirs, map_dir_names, mkdir_p


def parse_cl(argv):
    parser = ArgumentParser()
    parser.add_argument("root", metavar="ROOT_DIR", help="root dir")
    return parser.parse_args(argv[1:])


def main(argv):
    args = parse_cl(argv)
    data_dirs = get_data_dirs(root=args.root)
    name_map = map_dir_names(data_dirs)
    this_dir = os.path.dirname(os.path.abspath(__file__))
    parent = os.path.dirname(this_dir)
    patterns_dir = os.path.join(parent, "patterns")
    mkdir_p(patterns_dir)
    for d, name in sorted(name_map.items(), key=operator.itemgetter(1)):
        make_symlink_patterns.main(
            ["dummy", d, "-o", patterns_dir, "-t", name]
        )


if __name__ == "__main__":
    main(sys.argv)
