---
name: idr0003-breker-plasticity/screenA
version: 1

defaults:
    # Should the column be processed when creating bulk-annotations (yes/no)
    include: no
    # Columns type of the bulk-annotations column
    type: string

    # If non-empty a string used to separate multiple fields in a column
    # White space will be stripped
    split:
    # Should this column be included in the clients (yes/no)
    includeclient: yes
    # Should this column be visible in the clients, if no the column should be
    # hidden in the client but will still be indexed by the searcher (yes/no)
    visible: yes
    # Should empty values be omitted from the client display
    omitempty: yes

columns:

  - name: Gene Identifier
    include: yes
  - name: Gene Identifier
    clientname: Gene Identifier URL
    clientvalue: http://www.ensembl.org/id/{{ value }}
    include: yes
  - name: Gene Symbol
    include: yes
  - name: Experimental Condition [environmental stress]
    include: yes
  - name: Phenotype 1
    include: yes
  - name: Phenotype 1 Term Name
    include: yes
  - name: Phenotype 1 Term Accession
    include: yes
  - name: Phenotype 1 Term Accession
    clientname: Phenotype 1 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 2
    include: yes
  - name: Phenotype 2 Term Name
    include: yes
  - name: Phenotype 2 Term Accession
    include: yes
  - name: Phenotype 2 Term Accession
    clientname: Phenotype 2 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 3
    include: yes
  - name: Phenotype 3 Term Name
    include: yes
  - name: Phenotype 3 Term Accession
    include: yes
  - name: Phenotype 3 Term Accession
    clientname: Phenotype 3 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 4
    include: yes
  - name: Phenotype 4 Term Name
    include: yes
  - name: Phenotype 4 Term Accession
    include: yes
  - name: Phenotype 4 Term Accession
    clientname: Phenotype 4 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 5
    include: yes
  - name: Phenotype 5 Term Name
    include: yes
  - name: Phenotype 5 Term Accession
    include: yes
  - name: Phenotype 5 Term Accession
    clientname: Phenotype 5 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 6
    include: yes
  - name: Phenotype 6 Term Name
    include: yes
  - name: Phenotype 6 Term Accession
    include: yes
  - name: Phenotype 6 Term Accession
    clientname: Phenotype 6 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 7
    include: yes
  - name: Phenotype 7 Term Name
    include: yes
  - name: Phenotype 7 Term Accession
    include: yes
  - name: Phenotype 7 Term Accession
    clientname: Phenotype 7 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 8
    include: yes
  - name: Phenotype 8 Term Name
    include: yes
  - name: Phenotype 8 Term Accession
    include: yes
  - name: Phenotype 8 Term Accession
    clientname: Phenotype 8 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 9
    include: yes
  - name: Phenotype 9 Term Name
    include: yes
  - name: Phenotype 9 Term Accession
    include: yes
  - name: Phenotype 9 Term Accession
    clientname: Phenotype 9 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 10
    include: yes
  - name: Phenotype 10 Term Name
    include: yes
  - name: Phenotype 10 Term Accession
    include: yes
  - name: Phenotype 10 Term Accession
    clientname: Phenotype 10 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 11
    include: yes
  - name: Phenotype 11 Term Name
    include: yes
  - name: Phenotype 11 Term Accession
    include: yes
  - name: Phenotype 11 Term Accession
    clientname: Phenotype 11 Term Accession URL
    clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
    include: yes
  - name: Phenotype 12
    include: yes
  - name: Phenotype 13
    include: yes
  - name: Phenotype 14
    include: yes
    
# Advanced options (experimental)
advanced:
    # If a map-annotation is attached to a well also attach it to all images
    # in the well
    well_to_images: yes
