#!/usr/bin/env python

import sys
import os
import errno
import string

import make_screen

ROOT = "/idr/filesets/idr0004-thorpe-rad52/Rad52_old/Rad52"
SCREENS_DIR = os.path.join(os.pardir, "screens")
PLATES_DIR = os.path.join(os.pardir, "screenA/plates")
REL_SCREENS_DIR = "idr0004-thorpe-rad52/screens"

ALL_EXPECTED_BASENAMES = set(
    "%s%s" % (c, i) for c in string.lowercase[:8] for i in xrange(1, 13)
)


def main(argv):
    try:
        os.makedirs(SCREENS_DIR)
        os.makedirs(PLATES_DIR)
    except OSError as e:
        if e.errno == errno.ENOENT:
            pass
    basenames = os.listdir(ROOT)
    with open("stats.txt", "w") as fo:
        for bn in basenames:
            d = os.path.join(ROOT, bn)
            if not os.path.isdir(d):
                continue
            all_basenames = set(
                _ for _ in os.listdir(d) if os.path.isfile(os.path.join(d, _))
            )
            expected = len(all_basenames & ALL_EXPECTED_BASENAMES)
            fo.write("%s\t%d(%d)\n" % (d, len(all_basenames), expected))
            screen_fn = os.path.join(SCREENS_DIR, "%s.screen" % bn)
            make_screen.main(["dummy", d, "-o", screen_fn, "-p", bn])
            plate_fn = os.path.join(PLATES_DIR, bn)
            with open(plate_fn, "w") as plate_file:
                plate_file.write("%s/%s.screen\n" % (REL_SCREENS_DIR, bn))


if __name__ == "__main__":
    main(sys.argv)
