---
name: idr0013-neumann-mitocheck/screenA
version: 2

defaults:
    # Should the column be processed when creating bulk-annotations (yes/no)
    include: no
    # Columns type of the bulk-annotations column
    type: string

    # If non-empty a string used to separate multiple fields in a column
    # White space will be stripped
    split:
    # Should this column be included in the clients (yes/no)
    includeclient: yes
    # Should this column be visible in the clients, if no the column should be
    # hidden in the client but will still be indexed by the searcher (yes/no)
    visible: yes
    # Should empty values be omitted from the client display
    omitempty: yes

columns:

  - name: Characteristics [Cell Line]
    clientname: Cell Line
    include: yes

  - name: Control Type
    include: yes
  - name: Control Comments
    include: yes

  - name: Quality Control
    include: yes
  - name: Channels
    include: yes
  - name: Comments
    include: yes

  - name: Potential Mitotic Hit At Gene Level
    include: yes
  - name: Validated Mitotic Hit At Gene Level
    include: yes

  - name: Has Phenotype
    include: yes
  - name: Phenotype Annotation Level
    include: yes


######################################################################
# mapr groups
######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
      - name: Characteristics [Organism]
        clientname: Organism
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/sirna
      columns:
      - name: siRNA Identifier
        include: yes
      - name: Mitocheck siRNA Identifier
        include: yes
      - name: Sense Sequence
        include: yes
      - name: Antisense Sequence
        include: yes
      - name: Original Gene Target
        include: yes
      - name: Reagent Design Gene Annotation Build
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/gene
      columns:
      - name: Gene Identifier
        include: yes
      - name: Gene Identifier
        clientname: Gene Identifier URL
        clientvalue: http://www.ensembl.org/id/{{ value }}
        include: yes
      - name: Gene Symbol
        include: yes
      - name: Gene Annotation Comments
        include: yes
      - name: Analysis Gene Annotation Build
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 1
        clientname: Phenotype
        include: yes
      - name: Phenotype 1 Term Name
        clientname: Phenotype Term Name
        include: yes 
      - name: Phenotype 1 Term Accession
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 1 Term Accession
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 2
        clientname: Phenotype
        include: yes
      - name: Phenotype 2 Term Name
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 2 Term Accession
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 2 Term Accession
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 3
        clientname: Phenotype
        include: yes
      - name: Phenotype 3 Term Name
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 3 Term Accession
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 3 Term Accession
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 4
        clientname: Phenotype
        include: yes
      - name: Phenotype 4 Term Name a
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 4 Term Accession a
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 4 Term Accession a
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
        include: yes
      - name: Phenotype 4 Term Name b
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 4 Term Accession b
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 4 Term Accession b
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 5
        clientname: Phenotype
        include: yes
      - name: Phenotype 5 Term Name a
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 5 Term Accession a
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 5 Term Accession a
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
        include: yes
      - name: Phenotype 5 Term Name b
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 5 Term Accession b
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 5 Term Accession b
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 6
        clientname: Phenotype
        include: yes
      - name: Phenotype 6 Term Name a
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 6 Term Accession a
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 6 Term Accession a
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
        include: yes
      - name: Phenotype 6 Term Name b
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 6 Term Accession b
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 6 Term Accession b
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 7
        clientname: Phenotype
        include: yes
      - name: Phenotype 7 Term Name
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 7 Term Accession
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 7 Term Accession
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 8
        clientname: Phenotype
        include: yes
      - name: Phenotype 8 Term Name
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 8 Term Accession
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 8 Term Accession
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 9
        clientname: Phenotype
        include: yes
      - name: Phenotype 9 Term Name
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 9 Term Accession
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 9 Term Accession
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 10
        clientname: Phenotype
        include: yes
      - name: Phenotype 10 Term Name
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 10 Term Accession
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 10 Term Accession
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 11
        clientname: Phenotype
        include: yes
      - name: Phenotype 11 Term Name
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 11 Term Accession
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 11 Term Accession
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 12
        clientname: Phenotype
        include: yes
      - name: Phenotype 12 Term Name
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 12 Term Accession
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 12 Term Accession
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 13
        clientname: Phenotype
        include: yes
      - name: Phenotype 13 Term Name
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 13 Term Accession
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 13 Term Accession
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 14
        clientname: Phenotype
        include: yes
      - name: Phenotype 14 Term Name a
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 14 Term Accession a
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 14 Term Accession a
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
        include: yes
      - name: Phenotype 14 Term Name b
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 14 Term Accession b
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 14 Term Accession b
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 15
        clientname: Phenotype
        include: yes
      - name: Phenotype 15 Term Name
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 15 Term Accession
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 15 Term Accession
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 16
        clientname: Phenotype
        include: yes
      - name: Phenotype 16 Term Name
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 16 Term Accession
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 16 Term Accession
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 17
        clientname: Phenotype
        include: yes
      - name: Phenotype 17 Term Name
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 17 Term Accession
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 17 Term Accession
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 18
        clientname: Phenotype
        include: yes
      - name: Phenotype 18 Term Name
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 18 Term Accession
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 18 Term Accession
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
        include: yes

# Advanced options (experimental)
advanced:
    # If a map-annotation is attached to a well also attach it to all images
    # in the well
    well_to_images: yes

    # TODO: Primary key config should be in a global config
    ignore_missing_primary_key: yes
    primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
      - Organism
    - namespace: openmicroscopy.org/mapr/sirna
      keys:
      - siRNA Identifier
    - namespace: openmicroscopy.org/mapr/gene
      keys:
      - Gene Identifier
      - Gene Symbol
    - namespace: openmicroscopy.org/mapr/phenotype
      keys:
      - Phenotype
