---
name: idr0026-weigelin-immunotherapy/experimentA
version: 2

defaults:
    # Should the column be processed when creating bulk-annotations (yes/no)
    include: no
    # Columns type of the bulk-annotations column
    type: string

    # If non-empty a string used to separate multiple fields in a column
    # White space will be stripped
    split:
    # Should this column be included in the clients (yes/no)
    includeclient: yes
    # Should this column be visible in the clients, if no the column should be
    # hidden in the client but will still be indexed by the searcher (yes/no)
    visible: yes
    # Should empty values be omitted from the client display
    omitempty: yes

columns:

  - name: Characteristics [Strain]
    clientname: Strain
    include: yes
  - name: Characteristics [Sex]
    clientname: Sex
    include: yes
  - name: Characteristics [Age]
    clientname: Age
    include: yes
  - name: Characteristics [Individual]
    clientname: Individual
    include: yes
  - name: Characteristics [Organism Part]
    clientname: Organism Part
    include: yes
  - name: Characteristics [Clinical Information]
    clientname: Clinical Information
    include: yes
  - name: Experimental Condition [Treatment Timepoint]
    clientname: Treatment Timepoint
    include: yes
  - name: Experimental Condition [Treatment]
    clientname: Treatment
    include: yes
  - name: Experimental Condition [Sampling Timepoint]
    clientname: Sampling Timepoint
    include: yes

  - name: Comment [Raw Data Capture]
    clientname: Raw Data Capture
    include: yes
  - name: Comment [Field]
    clientname: Field
    include: yes

  - name: Channels
    include: yes

  - name: Comment [Image File Type]
    clientname: Image File Type
    include: yes

  - name: Has Phenotype
    include: yes
  - name: Phenotype Annotation Level
    include: yes


######################################################################
# mapr groups
######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
      - name: Characteristics [Organism]
        clientname: Organism
        include: yes


  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 1
        clientname: Phenotype
        include: yes
      - name: Phenotype 1 Term Name
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 1 Term Accession
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 1 Term Accession
        clientname: Phenotype Term Accession URL
        clientvalue: http://purl.obolibrary.org/obo/{{ value|urlencode }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 2
        clientname: Phenotype
        include: yes
      - name: Phenotype 2 Term Name
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 2 Term Accession
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 2 Term Accession
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value|urlencode }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 3
        clientname: Phenotype
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 4
        clientname: Phenotype
        include: yes
      - name: Phenotype 4 Term Name
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 4 Term Accession
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 4 Term Accession
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value|urlencode }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 5
        clientname: Phenotype
        include: yes
      - name: Phenotype 5 Term Name
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype 5 Term Accession
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype 5 Term Accession
        clientname: Phenotype Term Accession URL
        clientvalue: http://www.ebi.ac.uk/cmpo/{{ value|urlencode }}
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 6
        clientname: Phenotype
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 7
        clientname: Phenotype
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype 8
        clientname: Phenotype
        include: yes

# Advanced options (experimental)
advanced:
    # If a map-annotation is attached to a well also attach it to all images
    # in the well
    well_to_images: yes

    # TODO: Primary key config should be in a global config
    ignore_missing_primary_key: yes
    primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
      - Organism
    - namespace: openmicroscopy.org/mapr/phenotype
      keys:
      - Phenotype
