#!/usr/bin/env python

import sys
import os
import glob
import errno
import make_screen

ROOT = ("/uod/idr/filesets/idr0011-thorpe-Dad4/20150826-peter_thorpe/")

SCREENS = {
    "A": (
        ("T37 x deletion library", 2, "*/", {}),
    ),
    "B": (
        ("T34 x TS", 6, "*/", {}),
    ),
    "C": (
        ("Stinger plates-extra images screen T37 x deletion library", 1, "*/", {
            "Plate Stinger-Target 2-A-used pics": "Target-2-A",
            "Plate-Stinger-Target2-B-used pics": "Target-2-B",
            "Plate Stinger-Target 1-B-used pics": "Target-1-B",
            "Plate Stinger-Target 1-A-used pics": "Target-1-A",
        }),
    ),
    "E": (
        ("Stinger plates-extra images screen T34 x TS", 1, "", {}),
    ),
    "D": (
        ("Stinger plates-extra images screen T34 x TS-more repeats", 3, "", {}),
    ),
}

CHANNEL_NAMES = ("Blue", "Green", "Red", "Yellow")

def main(argv):
    study_root = os.path.dirname(os.path.abspath(__file__))
    screens_dir = os.path.join(study_root, "screens")
    for letter, directories in sorted(SCREENS.items()):

        tsv = "screen%s/idr0011-screen%s-plates.tsv" % (letter, letter)
        plates_fn = os.path.join(study_root, tsv)
        try:
            os.makedirs(screens_dir)
            os.makedirs(os.path.dirname(plates_fn))
        except OSError as e:
            if e.errno == errno.ENOENT:
                pass

        with open(plates_fn, "w") as fp:
            for directory, fields, extra, overrides in directories:
                basenames = glob.glob("%s%s/%s*" % (ROOT, directory, extra))
                for bn in basenames:
                    if not os.path.isdir(bn): continue
                    print bn
                    screen_name = os.path.basename(bn)
                    screen_name = overrides.get(screen_name, screen_name)
                    screen_name = screen_name.replace("-used pics", "")
                    for ch in CHANNEL_NAMES:
                        screen_name = screen_name.replace("%s-A-TS" % ch, "TS-%s-A" % ch)
                        screen_name = screen_name.replace("%s-A_TS" % ch, "TS-%s-A" % ch)  # Special case
                        screen_name = screen_name.replace("%s-B-TS" % ch, "TS-%s-B" % ch)
                    p1 = screen_name.find("(")
                    p2 = screen_name.find(")")
                    if p1 > 0 and p2 > 0:
                        screen_name = screen_name[0:p1-1]
                        screen_name += screen_name[p2:]
                    screen_fn = os.path.join(screens_dir, "%s.screen" % screen_name)
                    screen_rel = os.path.join("..", "screens", "%s.screen" % screen_name)
                    make_screen.main(["dummy", bn,
                                      "-o", screen_fn,
                                      "-p", bn,
                                      "-f", str(fields)])
                    fp.write("%s\t%s\n" %
                        (screen_name, screen_rel))


if __name__ == "__main__":
    main(sys.argv)
