---
name: idr0040-aymoz-singlecell/experimentA
version: 1

defaults:
    # Should the column be processed when creating bulk-annotations (yes/no)
    include: no
    # Columns type of the bulk-annotations column
    type: string

    # If non-empty a string used to separate multiple fields in a column
    # White space will be stripped
    split: ;
    # Should this column be included in the clients (yes/no)
    includeclient: yes
    # Should this column be visible in the clients, if no the column should be
    # hidden in the client but will still be indexed by the searcher (yes/no)
    visible: yes
    # Should empty values be omitted from the client display
    omitempty: yes

columns:

  - name: Characteristics [Strain]
    clientname: Strain
    include: yes
  - name: Characteristics [Genotype]
    clientname: Genotype
    include: yes
  - name: Characteristics [Mating Type]
    clientname: Mating Type
    include: yes
  - name: Term Source Accession
    clientname: EFO term
    include: yes
  - name: Experimental Condition [Treatment]
    clientname: Treatment
    include: yes
  - name: Channels
    clientname: Channels
    include: yes

######################################################################
# mapr groups
######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
      - name: Characteristics [Organism]
        clientname: Organism
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/gene
      columns:
      - name: Comment [Gene Identifier 1]
        clientname: Gene Identifier
        include: yes
      - name: Comment [Gene Identifier 1]
        clientname: Gene Identifier URL
        clientvalue: http://www.yeastgenome.org/locus/{{ value|urlencode }}/overview
        include: yes
      - name: Comment [Gene Symbol 1]
        clientname: Gene Symbol
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/gene
      columns:
      - name: Comment [Gene Identifier 2]
        clientname: Gene Identifier
        include: yes
      - name: Comment [Gene Identifier 2]
        clientname: Gene Identifier URL
        clientvalue: http://www.yeastgenome.org/locus/{{ value|urlencode }}/overview
        include: yes
      - name: Comment [Gene Symbol 2]
        clientname: Gene Symbol
        include: yes
