#!/usr/bin/env python

import sys
import os
import errno
import make_screen

ROOT = "/uod/idr/filesets/idr0025-stadler-proteinatlas/20160525-rawdata"
BASENAMES = [
    '10x images plate 1',
    '10x images plate 2',
    '10x images plate 3',
]


def main(argv):
    this_dir = os.path.dirname(os.path.abspath(__file__))
    parent = os.path.dirname(this_dir)
    screens_dir = os.path.join(parent, "screens")
    plates_fn = os.path.join(parent, "screenA", "idr0025-screenA-plates.tsv")
    rel_screens_dir = os.path.join(os.pardir, "screens")  # wrt plates_fn
    try:
        os.makedirs(screens_dir)
        os.makedirs(os.path.dirname(plates_fn))
    except OSError as e:
        if e.errno == errno.ENOENT:
            pass
    with open(plates_fn, "w") as fp:
        for bn in BASENAMES:
            d = os.path.join(ROOT, bn)
            screen_fn = os.path.join(screens_dir, "%s.screen" % bn)
            make_screen.main(["dummy", d, "-o", screen_fn, "-p", bn])
            fp.write("%s\t%s.screen\n" %
                     (bn, os.path.join(rel_screens_dir, bn)))


if __name__ == "__main__":
    main(sys.argv)
