name: Build
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: python -mpip install idr-utils/
      - name: Validate study files
        run: find . -type f -name '*study.txt' | sort | xargs python idr-utils/pyidr/study_parser.py --report --report-directory studies
      - name: Run other checks
        run: python idr-utils/scripts/travis-check.py
      - name: Create studies archive
        run: tar -zcvf studies.tar.gz studies
      - name: Upload studies archive as artifact
        uses: actions/upload-artifact@v2
        with:
          name: studies.tar.gz
          path: studies.tar.gz
